---
- name: validate required connection is configured
  fail:
    msg: "expected connection value to be set to network_cli, got {{ ansible_connection }}"
  when: ansible_connection != 'network_cli'

- name: "iosxr: enable netconf if not already enabled"
  iosxr_netconf:
    netconf_port: "{{ netconf_port }}"
    netconf_vrf:  "{{ netconf_vrf }}"
    state: present
